#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorNone)
#pragma config(Sensor, dgtl2,  rightSensor,    sensorSONAR_cm)
#pragma config(Sensor, dgtl6,  leftTouch,      sensorTouch)
#pragma config(Sensor, dgtl7,  rightTouch,     sensorTouch)
#pragma config(Sensor, dgtl8,  sonarCM,        sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, reversed, driveLeft, encoderPort, None)
#pragma config(Motor,  port6,           armMotor,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/******************
Pearl Vishen
Period 4
10/11/18
Assignment: Speed of Sound
Goal: Move to the block using sensors then wait for 5 seconds
Algorithm: Move forward
******************/

//Declaring Variables\\
void fwd(int speed);
void stp(int speed);
int target = 15;


task main()
{
    while(SensorValue[sonarCM]>target)  // While the SensorValue is less than the target(15) do this
   {
     fwd(SensorValue[sonarCM]*3);
   }


 stp(0);
}


//Defining Variables\\

void fwd(int speed)
{
	motor[rightMotor] = speed;
	motor[leftMotor] = speed;
}

void stp(int speed)
{
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(5000);
}
